### ISSUE TITLE
如何在gazebo环境实现

### ISSUE THREAD

**Issue by HitSZwang** [Derek-TH-Wang/quadruped_ctrl#1]
想问一下，如何在gazebo环境中实现mini cheetah 的控制呢？感谢

**Comment by Derek-TH-Wang** [comment]
需要把mini cheetah的算法抽出来，将仿真环境输出的传感器信息与算法输入接口对上，再把算法输出的机器人关节控制信号输出到仿真器，大概是这样的思路。我现在差不多把算法提取出来了，但是可能还有bug走不起来，与仿真器之间都是用ros通讯，你可以非常容易的把pybullet替换成gazebo。

**Comment by HitSZwang** [comment]
好的  以后互相探讨 谢谢

**Comment by HitSZwang** [comment]
为什么运行.launch  会报这种错Failed to call JM while setting current mode
[quadruped_ctrl-2] process has died [pid 20768, exit code 1, cmd /home/quadruped/champ_ws/devel/lib/quadruped_robot/quadruped_ctrl __name:=quadruped_ctrl __log:=/home/quadruped/.ros/log/08c5ca9a-f306-11ea-bb75-a08cfdbe3f9c/quadruped_ctrl-2.log].

**Comment by HitSZwang** [comment]
通过修改MPCLOCOMOTION，给他速度能走，但是Z轴会变大，代码中没有给Z方向的速度，奇怪

**Comment by Derek-TH-Wang** [comment]
代码里有bug，不过这个bug已经解决了，还没有上传

**Comment by HitSZwang** [comment]
能说下哪里有问题吗？感谢

**Comment by Derek-TH-Wang** [comment]
还有点小问题，过几天会上传代码

**Comment by Derek-TH-Wang** [comment]
代码已更新
