### ISSUE TITLE
我已经跑通了本仓库的项目，可以改变场景以及机器人步态。但是应该怎么控制机器人在仿真环境里自由行走呢？

### ISSUE THREAD

**Issue by mark9714** [Derek-TH-Wang/quadruped_ctrl#12]
![2021-12-20 14-44-31屏幕截图](https://user-images.githubusercontent.com/71640010/146725144-816f14db-6cce-4741-98bd-c310883ae766.png)

但是运行gamepad_ctrl.launch时候报错如图，所以我应该怎么控制机器人在仿真环境里运动？谢谢你。
![2021-12-20 14-57-29屏幕截图](https://user-images.githubusercontent.com/71640010/146725280-fee53b7d-e319-442d-85ff-c84ffa27ddad.png)

**Comment by Derek-TH-Wang** [comment]
需要安装joy 这个rospack，具体通过sudo apt-get install ros-melodic-joy指令

**Comment by mark9714** [comment]
好的，谢谢您的回答
