### ISSUE TITLE
trying on real robot, with walking_simulation.py

### ISSUE THREAD

**Issue by elpimous** [Derek-TH-Wang/quadruped_ctrl#13]
Hello Derek,
before going any further, with a c++ difficult code, 
I'd like to use your python file, to command my motors. (before doing same in c++)
Could you tell me what function i have to call, to sends to real robot motor boards, 
and what fonction to call, to receive motor values?

Am I right ? : 
inside  the fonction : `self.__get_data_from_sim()`
- I need to feed here my real IMU 10 values

inside the fonction : `self.__get_motor_joint_states()`
- need to query real motors controllers for joint_positions, joint_velocities, joint_torque and joint_names

and inside : 
`tau = self.cpp_gait_ctrller.torque_calculator(self.__convert_type(
            imu_data), self.__convert_type(leg_data["state"]))`
- It should tell me what values to sent to real motors controllers, correct ?

**Comment by Derek-TH-Wang** [comment]
yes, you're right

**Comment by elpimous** [comment]
Super @Derek-TH-Wang. 
So I have force to send to motors
And could you tell me where to pick values Position/velocity in the code, to send to real motors?!

**Comment by Derek-TH-Wang** [comment]
you can use 'legcommand' to send to the real robot.
'legcommand' struct is in legController file.
