### ISSUE TITLE
pubullet和控制器连接的思路

### ISSUE THREAD

**Issue by HitSZwang** [Derek-TH-Wang/quadruped_ctrl#2]
我大概是这样理解pybullet与控制器之间的互通,控制器接受pybullet的速度位置以及IMU数据  各个关节的位置和速度.控制器通过得到的数据,假如我给一个速度,他就会计算出各个关节的位置以及力,发送给pybullet.pybullet得到各个关节的位置 力 进行相应的运动,这样的理解对吗?

**Comment by Derek-TH-Wang** [comment]
对的。
你是哈工大深圳的研究生？

**Comment by HitSZwang** [comment]
是的

**Comment by HitSZwang** [comment]
为什么控制器给我的模型计算出的髋关节Hip值这么大变大，到-1。发送给控制器的hip数据都是0.00几，计算的数据很不正常，

**Comment by Derek-TH-Wang** [comment]
没太明白你的意思，可以贴图看一下

**Comment by HitSZwang** [comment]
我用 robot_mode cmd 1  力矩模式控制他站立，机器人直接跳起来了，KPKd值有问题吗？

**Comment by Derek-TH-Wang** [comment]
每次吗，还是有时候？

**Comment by HitSZwang** [comment]
对 应该是KpKd值的问题，力矩站立有点摇摇晃晃在Gazebo中，我运行robot_mode cmd 4 让他trot的时候，他直接跳起来旋转，但是trot的双脚离地是对的，这是什么原因呢

**Comment by Derek-TH-Wang** [comment]
不同仿真器仿真效果是不一样的，一般要改一些参数，比如KP、KD、MPC系数、仿真器中的摩擦力、关节阻尼等

**Comment by HitSZwang** [comment]
好的 谢谢，我也觉得应该是这些参数不对，我尝试了直接发送运动学逆解解出来的相位，前几步还是正常的，但是Z方向会越来越小，直接趴下。现在在尝试计算的力矩来控制，控制器通过雅克比计算出的力矩有问题，我直接输入控制器计算出的力矩，在你的pybullet是好用的，但是在gazebo环境中，他会跳起或者旋转。还不如采用计算出的相位，他还能走几步正常的。

**Comment by Derek-TH-Wang** [comment]
你主要研究四足哪一部分算法？

**Comment by HitSZwang** [comment]
我主要是做导航与路径规划

**Comment by HitSZwang** [comment]
/home/quadruped/Pictures/Screenshot from 2020-09-27 16-52-48.png
/home/quadruped/Pictures/Screenshot from 2020-09-27 16-54-22.png

**Comment by HitSZwang** [comment]
/home/quadruped/Pictures/Screenshot from 2020-10-19 10-35-36.png 
上台阶之后，出现前面的退这样是什么原因呢？

**Comment by HitSZwang** [comment]
![Screenshot from 2020-10-19 10-35-36](https://user-images.githubusercontent.com/63332427/96395532-7146ed00-11f7-11eb-9cbe-c85f97f6ae8f.png)
上台阶之后，出现前面的退这样是什么原因呢？

**Comment by Derek-TH-Wang** [comment]
这个台阶太高了会有问题，腿没有那么长，可以试试矮一点的。
