### ISSUE TITLE
Custom robot 

### ISSUE THREAD

**Issue by raess1** [Derek-TH-Wang/quadruped_ctrl#4]
Hey! 
I am trying out a difffent robot Urdf and it looks like this.
![9A35F2DC-CC76-488F-8479-84B9C75EBBA5](https://user-images.githubusercontent.com/6362413/99888637-a4452c00-2c4e-11eb-80d9-be45316493cb.jpeg)

![1B824112-A3A6-49EE-A457-0DAA3F03CD80](https://user-images.githubusercontent.com/6362413/99888729-26355500-2c4f-11eb-8da8-84bf3d2ec976.png)

 It can walk around like this but I can’t seem to find a way to get it to work normal. 

Do you have any suggestions on what can be the reason? 

Thanks 
RF

**Comment by Derek-TH-Wang** [comment]
It seems like the body height is to small, may be your robot is larger then mini cheetah, you can try to modify the body height, which can be found in a variable named '_body_height ' in ConvexMPCLocomotion.cpp line 79.
Another reason may be that the force calcualted from mpc is not right, then, you have to adjust the parameters about MPC.

**Comment by raess1** [comment]
Thanks for the feedback. Yeah its a bit bigger then mini cheetah. 

I tried to change the '_body_height ' in ConvexMPCLocomotion.cpp to `0.43` But then the robot had very strange motions. 

My specs are for the robot is around this: 
`cheetah._bodyMass = 6.0; //estimated at around 6 for K3lso
  cheetah._bodyLength = 0.245 * 2; //estimated to confirm
  cheetah._bodyWidth = 0.055 * 2; //estimated to confirm
  cheetah._bodyHeight = 0.095 * 2; //estimated to confirm
  cheetah._abadGearRatio = 9; // Specs for AK10-9
  cheetah._hipGearRatio = 9; // Specs for AK10-9
  cheetah._kneeGearRatio = 12.6; // Additional reduction for knee Specs from AK10-9 9 *1,4 = 12,6 (10T/14T)
  cheetah._abadLinkLength = 0.062;
  cheetah._hipLinkLength = 0.279523;
  //cheetah._kneeLinkLength = 0.175;
  //cheetah._maxLegLength = 0.384;
  cheetah._kneeLinkY_offset = 0.004; // need to check 
  //cheetah._kneeLinkLength = 0.20;
  cheetah._kneeLinkLength = 0.302314;
  cheetah._maxLegLength = 0.550;


  cheetah._motorTauMax = 6.f; // ?? To confirm
  cheetah._batteryV = 44; // 10S Lipo
  cheetah._motorKT = .095;  // this is flux linkage * pole pairs
  cheetah._motorR = 0.090;
  cheetah._jointDamping = .01;
  cheetah._jointDryFriction = .2;
  //cheetah._jointDamping = .0;
  //cheetah._jointDryFriction = .0; `

**Comment by Derek-TH-Wang** [comment]
the speces look good, the big probability could be the problem of calculating the force or toque(from mpc force to joint torque), maybe you could take a look at this part.

**Comment by raess1** [comment]
Okej good! And tips on what files and lines to look at? 🙃

**Comment by Derek-TH-Wang** [comment]
LegController and ConvexMPCLocomotion are two important files

**Comment by raess1** [comment]
So I got it up and running! :-) I just changed a few axis to negative in the urdf. 

Some questions tho: 
The controller fetches the mass from the urdf file. How do one knows that the controller is using the correct actuator torque? 

I set up the MiniCheetah.h with my values. But it does not seem to make any difference in the simulation. I can for example set `cheetah._motorTauMax = 1 `or ``cheetah._motorTauMax = 20` with same behavior in the simulation when using same mass in the urdf.

**Comment by Derek-TH-Wang** [comment]
Congratulations and thanks for writing down the questions, yes, some parameters in MiniCheetah.h are useless, because MIT use all the parameters to build simulator, but we use Pybullet and load URDF file to read most of the parameters. Only some kinematics parameters are used in calculation.
