### ISSUE TITLE
状态估计器

### ISSUE THREAD

**Issue by HitSZwang** [Derek-TH-Wang/quadruped_ctrl#5]
你有遇到这样的问题吗？状态估计器在Z方向产生变化之后，始终认为机器人在地面上。有没有什么好的方法解决状态估计器不准确的问题，感谢。

**Comment by Derek-TH-Wang** [comment]
状态估计器确实没有考虑Z方向变化，但是应该不会影响上楼梯或者斜面等情况，你是需要这个Z值变化吗？用来做什么？

**Comment by HitSZwang** [comment]
我感觉会影响上楼梯或斜面，状态估计器一直认为机器人在平面上走，跟在斜面上还是有很大区别的。
还有一个问题，他是根据摆动时间来判断触地状态的，在爬斜面刚开始的时候，由于斜面高，前腿摆动的Z值小，前腿已经落地了，但是代码会认为机器人跟在地面上一样，前腿还没有落地。这样就造成机器人在爬上斜面的时候特别不稳定。目前没有找到特别好的解决办法

**Comment by Derek-TH-Wang** [comment]
恩，还是有一定影响，但是斜面上稳定性试了一下貌似还可以，你说的特别不稳可以发个视频看一下是什么状态吗。
这个问题应该可以考虑改变身体姿态解决。

**Comment by 1219883141** [comment]
编译的时候出现了  cannot find cpp.so file
请问这个怎么解决

**Comment by NoDoubleBird** [comment]
> 编译的时候出现了 cannot find cpp.so file 请问这个怎么解决

在对应的python文件中你会找到这句话，原因是加载.so的文件路径不对，改一下就可以了
将so_file = self.path.replace('src/quadruped_ctrl', 'devel/lib/libquadruped_ctrl.so')改为so_file = self.path.replace('src/quadruped_ctrl', '/devel/lib/libquadruped_ctrl.so')
