### ISSUE TITLE
Deploy on a real robot

### ISSUE THREAD

**Issue by nicrusso7** [Derek-TH-Wang/quadruped_ctrl#6]
Hi,

Thank you for sharing your work.
How would you deploy this on a real robot?

Thanks!

**Comment by Derek-TH-Wang** [comment]
Thank you for your attention. If you want to deploy it on a real robot, you need to figure out the interface (IMU/joint data) between the algorithm and the robot. These interfaces are the same for the simulator and the real robot. You should input IMU and joint pos/vel etc. data to the controller, and the controller can output the joint torque required by the robot. Then the other work is to adjust the parameters.

**Comment by nicrusso7** [comment]
Thank you @Derek-TH-Wang, I'll play a little bit with this!
