### ISSUE TITLE
#include <unsupported/Eigen/MatrixFunctions>

### ISSUE THREAD

**Issue by elpimous** [Derek-TH-Wang/quadruped_ctrl#7]
Hi Derek,
I'd like to use your nice package, however, doesn't compile over ros !!

ubuntu 18.04
ros melodic
installed : sudo apt-get install libeigen3-dev

`[ 86%] Building CXX object quadruped_ctrl/CMakeFiles/quadruped_ctrl.dir/src/MPC_Ctrl/SolverMPC.cpp.o
/home/predator/catkin_ws/src/quadruped_ctrl/src/MPC_Ctrl/SolverMPC.cpp:7:10: fatal error: unsupported/Eigen/MatrixFunctions: Aucun fichier ou dossier de ce type
 #include <unsupported/Eigen/MatrixFunctions>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

quadruped_ctrl/CMakeFiles/quadruped_ctrl.dir/build.make:206: recipe for target 'quadruped_ctrl/CMakeFiles/quadruped_ctrl.dir/src/MPC_Ctrl/SolverMPC.cpp.o' failed
make[2]: *** [quadruped_ctrl/CMakeFiles/quadruped_ctrl.dir/src/MPC_Ctrl/SolverMPC.cpp.o] Error 1
make[2]: *** Attente des tâches non terminées....
In file included from /home/predator/catkin_ws/src/quadruped_ctrl/src/MPC_Ctrl/SparseCMPC_Math.cpp:3:0:
/usr/include/eigen3/unsupported/Eigen/MatrixFunctions:17:10: fatal error: Eigen/Core: Aucun fichier ou dossier de ce type
 #include <Eigen/Core>
          ^~~~~~~~~~~~
compilation terminated.

quadruped_ctrl/CMakeFiles/quadruped_ctrl.dir/build.make:134: recipe for target 'quadruped_ctrl/CMakeFiles/quadruped_ctrl.dir/src/MPC_Ctrl/SparseCMPC_Math.cpp.o' failed
make[2]: *** [quadruped_ctrl/CMakeFiles/quadruped_ctrl.dir/src/MPC_Ctrl/SparseCMPC_Math.cpp.o] Error 1
CMakeFiles/Makefile2:567: recipe for target 'quadruped_ctrl/CMakeFiles/quadruped_ctrl.dir/all' failed
make[1]: *** [quadruped_ctrl/CMakeFiles/quadruped_ctrl.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed
`
Please, any help ?!

Thanks a lot.
Vincent

**Comment by Derek-TH-Wang** [comment]
Try "sudo ln -s /usr/include/eigen3/Eigen /usr/include/Eigen".

**Comment by elpimous** [comment]
HEHE !! WORKING !
Thanks a lot Derek !
